# Purpose: generate script to scrape NFL coaching data from
#   pro-football-reference.com

# load in libraries
library(qdapRegex)
library(RCurl)
library(XML)

# load in list of url's for coach-specific pages from file "CoachURLs.txt"
# urls generated using xml-sitemaps.com

urlList <- c('http://www.pro-football-reference.com/coaches/AbboFa0.htm' ,
             'http://www.pro-football-reference.com/coaches/AlbeFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/AlexDo0.htm' ,
             'http://www.pro-football-reference.com/coaches/AlleDe0.htm' ,
             'http://www.pro-football-reference.com/coaches/AlleGe0.htm' ,
             'http://www.pro-football-reference.com/coaches/AndeHu0.htm' ,
             'http://www.pro-football-reference.com/coaches/AndrRo0.htm' ,
             'http://www.pro-football-reference.com/coaches/AriaBr0.htm' ,
             'http://www.pro-football-reference.com/coaches/ArmsJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/ArmsNe0.htm' ,
             'http://www.pro-football-reference.com/coaches/ArnsBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/AustBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/BachJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/BallHe0.htm' ,
             'http://www.pro-football-reference.com/coaches/BarrSh0.htm' ,
             'http://www.pro-football-reference.com/coaches/BarrNo0.htm' ,
             'http://www.pro-football-reference.com/coaches/BateJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/BattDi0.htm' ,
             'http://www.pro-football-reference.com/coaches/BattCl0.htm' ,
             'http://www.pro-football-reference.com/coaches/BaugSa0.htm' ,
             'http://www.pro-football-reference.com/coaches/BehmBu0.htm' ,
             'http://www.pro-football-reference.com/coaches/BeliBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/BellBe0.htm' ,
             'http://www.pro-football-reference.com/coaches/BengPh0.htm' ,
             'http://www.pro-football-reference.com/coaches/BennLe0.htm' ,
             'http://www.pro-football-reference.com/coaches/BergDu0.htm' ,
             'http://www.pro-football-reference.com/coaches/BerrRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/BerrPu0.htm' ,
             'http://www.pro-football-reference.com/coaches/BettTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/BezdHu0.htm' ,
             'http://www.pro-football-reference.com/coaches/BierSc0.htm' ,
             'http://www.pro-football-reference.com/coaches/BileEd0.htm' ,
             'http://www.pro-football-reference.com/coaches/BillBr0.htm' ,
             'http://www.pro-football-reference.com/coaches/BlacLi0.htm' ,
             'http://www.pro-football-reference.com/coaches/BlooJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/BolaPa0.htm' ,
             'http://www.pro-football-reference.com/coaches/BowlTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/BradGu0.htm' ,
             'http://www.pro-football-reference.com/coaches/BranJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/BrenWa0.htm' ,
             'http://www.pro-football-reference.com/coaches/BrewUn0.htm' ,
             'http://www.pro-football-reference.com/coaches/BricCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/BridFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/BrilMa0.htm' ,
             'http://www.pro-football-reference.com/coaches/BrooRi0.htm' ,
             'http://www.pro-football-reference.com/coaches/BrowPa0.htm' ,
             'http://www.pro-football-reference.com/coaches/BrunFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/BryaJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/BugeJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/BullHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/BurnJe0.htm' ,
             'http://www.pro-football-reference.com/coaches/CablTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/CaldJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/CallBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/CameCa0.htm' ,
             'http://www.pro-football-reference.com/coaches/CampDa1.htm' ,
             'http://www.pro-football-reference.com/coaches/CampHu0.htm' ,
             'http://www.pro-football-reference.com/coaches/CampMa0.htm' ,
             'http://www.pro-football-reference.com/coaches/CampDa0.htm' ,
             'http://www.pro-football-reference.com/coaches/CapeDo0.htm' ,
             'http://www.pro-football-reference.com/coaches/CarrPe0.htm' ,
             'http://www.pro-football-reference.com/coaches/CarsBu0.htm' ,
             'http://www.pro-football-reference.com/coaches/CaseEd0.htm' ,
             'http://www.pro-football-reference.com/coaches/CawtPe0.htm' ,
             'http://www.pro-football-reference.com/coaches/ChamGu0.htm' ,
             'http://www.pro-football-reference.com/coaches/ChecCo0.htm' ,
             'http://www.pro-football-reference.com/coaches/ChevJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ChilBr0.htm' ,
             'http://www.pro-football-reference.com/coaches/ChriJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ChudRo0.htm' ,
             'http://www.pro-football-reference.com/coaches/ClarAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/ClarDu0.htm' ,
             'http://www.pro-football-reference.com/coaches/ClarMo0.htm' ,
             'http://www.pro-football-reference.com/coaches/ClarPo0.htm' ,
             'http://www.pro-football-reference.com/coaches/CofaSt0.htm' ,
             'http://www.pro-football-reference.com/coaches/CollBl0.htm' ,
             'http://www.pro-football-reference.com/coaches/CollJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/ConkRe0.htm' ,
             'http://www.pro-football-reference.com/coaches/ConzJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/CornAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/CoryDo0.htm' ,
             'http://www.pro-football-reference.com/coaches/CoslBr0.htm' ,
             'http://www.pro-football-reference.com/coaches/CougFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/CougTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/CowhBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/CreiMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/CrenRo0.htm' ,
             'http://www.pro-football-reference.com/coaches/CrowCl0.htm' ,
             'http://www.pro-football-reference.com/coaches/CrowJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/CunnGu0.htm' ,
             'http://www.pro-football-reference.com/coaches/DaugRu0.htm' ,
             'http://www.pro-football-reference.com/coaches/DaviAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/DaviBu0.htm' ,
             'http://www.pro-football-reference.com/coaches/DawsRe0.htm' ,
             'http://www.pro-football-reference.com/coaches/DeGrDu0.htm' ,
             'http://www.pro-football-reference.com/coaches/DelRJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/DellHe0.htm' ,
             'http://www.pro-football-reference.com/coaches/DeplJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/DeviDa0.htm' ,
             'http://www.pro-football-reference.com/coaches/DevoHu0.htm' ,
             'http://www.pro-football-reference.com/coaches/DietLo0.htm' ,
             'http://www.pro-football-reference.com/coaches/DiMeLu0.htm' ,
             'http://www.pro-football-reference.com/coaches/DitkMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/DoheMe0.htm' ,
             'http://www.pro-football-reference.com/coaches/DoneAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/DoolJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/DoraGu0.htm' ,
             'http://www.pro-football-reference.com/coaches/DoudJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/DoveBo0.htm' ,
             'http://www.pro-football-reference.com/coaches/DowhRo0.htm' ,
             'http://www.pro-football-reference.com/coaches/DrisPa0.htm' ,
             'http://www.pro-football-reference.com/coaches/DrisWa0.htm' ,
             'http://www.pro-football-reference.com/coaches/DrulCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/DungTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/EdwaBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/EdwaCa0.htm' ,
             'http://www.pro-football-reference.com/coaches/EdwaHe0.htm' ,
             'http://www.pro-football-reference.com/coaches/EdwaTu0.htm' ,
             'http://www.pro-football-reference.com/coaches/ErdeEd0.htm' ,
             'http://www.pro-football-reference.com/coaches/ErhaRo0.htm' ,
             'http://www.pro-football-reference.com/coaches/EricDe0.htm' ,
             'http://www.pro-football-reference.com/coaches/EricHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/EwarCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/EwbaWe0.htm' ,
             'http://www.pro-football-reference.com/coaches/FairCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/FalcGu0.htm' ,
             'http://www.pro-football-reference.com/coaches/FassJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/FaulJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/FausFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/FearTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/FeldMa0.htm' ,
             'http://www.pro-football-reference.com/coaches/FewePe0.htm' ,
             'http://www.pro-football-reference.com/coaches/FilcFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/FishJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/FishJe0.htm' ,
             'http://www.pro-football-reference.com/coaches/FlahRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/FlorTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/FolwBo0.htm' ,
             'http://www.pro-football-reference.com/coaches/FontWa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ForsJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ForzRi0.htm' ,
             'http://www.pro-football-reference.com/coaches/FoxxJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/FrazLe0.htm' ,
             'http://www.pro-football-reference.com/coaches/FrieBe0.htm' ,
             'http://www.pro-football-reference.com/coaches/GailCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/GanzFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/GarrBu0.htm' ,
             'http://www.pro-football-reference.com/coaches/GarrJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/GettMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/GibbJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/GibrAb0.htm' ,
             'http://www.pro-football-reference.com/coaches/GibsGe0.htm' ,
             'http://www.pro-football-reference.com/coaches/GilbKe0.htm' ,
             'http://www.pro-football-reference.com/coaches/GillFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/GillSi0.htm' ,
             'http://www.pro-football-reference.com/coaches/GillHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/GilmHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/GlanJe0.htm' ,
             'http://www.pro-football-reference.com/coaches/GoleAr0.htm' ,
             'http://www.pro-football-reference.com/coaches/GrahOt0.htm' ,
             'http://www.pro-football-reference.com/coaches/GranBu0.htm' ,
             'http://www.pro-football-reference.com/coaches/GreeDe0.htm' ,
             'http://www.pro-football-reference.com/coaches/GregFo0.htm' ,
             'http://www.pro-football-reference.com/coaches/GrifHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/GrigTe0.htm' ,
             'http://www.pro-football-reference.com/coaches/GrohAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/GrudJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/GrudJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/HainHi0.htm' ,
             'http://www.pro-football-reference.com/coaches/HalaGe0.htm' ,
             'http://www.pro-football-reference.com/coaches/HaleTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/HandPh0.htm' ,
             'http://www.pro-football-reference.com/coaches/HandRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/HaniJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/HanlBo0.htm' ,
             'http://www.pro-football-reference.com/coaches/HanlDi0.htm' ,
             'http://www.pro-football-reference.com/coaches/HansHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/HarbJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/HarbJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/HaslJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/HeckNo0.htm' ,
             'http://www.pro-football-reference.com/coaches/HeffEr0.htm' ,
             'http://www.pro-football-reference.com/coaches/HegaJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/HeinMe0.htm' ,
             'http://www.pro-football-reference.com/coaches/HeldJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/HendGu0.htm' ,
             'http://www.pro-football-reference.com/coaches/HendDu0.htm' ,
             'http://www.pro-football-reference.com/coaches/HennDa0.htm' ,
             'http://www.pro-football-reference.com/coaches/HenrPe0.htm' ,
             'http://www.pro-football-reference.com/coaches/HessWa0.htm' ,
             'http://www.pro-football-reference.com/coaches/HickHo0.htm' ,
             'http://www.pro-football-reference.com/coaches/HickMa0.htm' ,
             'http://www.pro-football-reference.com/coaches/HiggAu0.htm' ,
             'http://www.pro-football-reference.com/coaches/HollBo0.htm' ,
             'http://www.pro-football-reference.com/coaches/HolmMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/HoloMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/HoltLo0.htm' ,
             'http://www.pro-football-reference.com/coaches/HorwAr0.htm' ,
             'http://www.pro-football-reference.com/coaches/HoweJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/HudsTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/HuffKe0.htm' ,
             'http://www.pro-football-reference.com/coaches/HughEd0.htm' ,
             'http://www.pro-football-reference.com/coaches/HughTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/HuntHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ImlaTu0.htm' ,
             'http://www.pro-football-reference.com/coaches/InfaLi0.htm' ,
             'http://www.pro-football-reference.com/coaches/IsbeCe0.htm' ,
             'http://www.pro-football-reference.com/coaches/IvyxPo0.htm' ,
             'http://www.pro-football-reference.com/coaches/JackHu0.htm' ,
             'http://www.pro-football-reference.com/coaches/JaurDi0.htm' ,
             'http://www.pro-football-reference.com/coaches/JoesHe0.htm' ,
             'http://www.pro-football-reference.com/coaches/JohnBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/JohnHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/JohnJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/JohnLu0.htm' ,
             'http://www.pro-football-reference.com/coaches/JollAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/JoneJu0.htm' ,
             'http://www.pro-football-reference.com/coaches/JoneRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/KarcBu0.htm' ,
             'http://www.pro-football-reference.com/coaches/KellCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/KendJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/KeogJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/KhayEd0.htm' ,
             'http://www.pro-football-reference.com/coaches/KiesWa0.htm' ,
             'http://www.pro-football-reference.com/coaches/KiffLa0.htm' ,
             'http://www.pro-football-reference.com/coaches/KnoxCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/KopfHe0.htm' ,
             'http://www.pro-football-reference.com/coaches/KoppWa0.htm' ,
             'http://www.pro-football-reference.com/coaches/KotiRi0.htm' ,
             'http://www.pro-football-reference.com/coaches/KraeOl0.htm' ,
             'http://www.pro-football-reference.com/coaches/KromAa0.htm' ,
             'http://www.pro-football-reference.com/coaches/KubaEd0.htm' ,
             'http://www.pro-football-reference.com/coaches/KubiGa0.htm' ,
             'http://www.pro-football-reference.com/coaches/KuhaJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/KuhlHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/KushFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/LairJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/LambCu0.htm' ,
             'http://www.pro-football-reference.com/coaches/LandTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/LeBeDi0.htm' ,
             'http://www.pro-football-reference.com/coaches/LemmWa0.htm' ,
             'http://www.pro-football-reference.com/coaches/LeonJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/LevyMa0.htm' ,
             'http://www.pro-football-reference.com/coaches/LewiAr0.htm' ,
             'http://www.pro-football-reference.com/coaches/LewiMa0.htm' ,
             'http://www.pro-football-reference.com/coaches/LineSc0.htm' ,
             'http://www.pro-football-reference.com/coaches/LombVi0.htm' ,
             'http://www.pro-football-reference.com/coaches/LyonLe0.htm' ,
             'http://www.pro-football-reference.com/coaches/MackJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/McPhDi0.htm' ,
             'http://www.pro-football-reference.com/coaches/MaddJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/MahrLo0.htm' ,
             'http://www.pro-football-reference.com/coaches/MalaRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/MangEr0.htm' ,
             'http://www.pro-football-reference.com/coaches/MarcTe0.htm' ,
             'http://www.pro-football-reference.com/coaches/MariRo0.htm' ,
             'http://www.pro-football-reference.com/coaches/MariSt0.htm' ,
             'http://www.pro-football-reference.com/coaches/MarrDo0.htm' ,
             'http://www.pro-football-reference.com/coaches/MarsBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/MartMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/MathNe0.htm' ,
             'http://www.pro-football-reference.com/coaches/MazuJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/McCaDo0.htm' ,
             'http://www.pro-football-reference.com/coaches/McCaMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/McCoMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/McCoMi1.htm' ,
             'http://www.pro-football-reference.com/coaches/McCuPe0.htm' ,
             'http://www.pro-football-reference.com/coaches/McDaJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/McEwCa0.htm' ,
             'http://www.pro-football-reference.com/coaches/McGaAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/McGiDa0.htm' ,
             'http://www.pro-football-reference.com/coaches/McIlWa0.htm' ,
             'http://www.pro-football-reference.com/coaches/McKaJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/McKeEd0.htm' ,
             'http://www.pro-football-reference.com/coaches/McLeRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/McMiAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/McPeBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/McVaJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/MeagJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/MehrHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/MeyeKe0.htm' ,
             'http://www.pro-football-reference.com/coaches/MeyeRo0.htm' ,
             'http://www.pro-football-reference.com/coaches/MichWa0.htm' ,
             'http://www.pro-football-reference.com/coaches/MichJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/MillRe0.htm' ,
             'http://www.pro-football-reference.com/coaches/MillWa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ModzDi0.htm' ,
             'http://www.pro-football-reference.com/coaches/MoelGa0.htm' ,
             'http://www.pro-football-reference.com/coaches/MoleKe0.htm' ,
             'http://www.pro-football-reference.com/coaches/MoraJi1.htm' ,
             'http://www.pro-football-reference.com/coaches/MoraJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/MoraCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/MornMa0.htm' ,
             'http://www.pro-football-reference.com/coaches/MorrRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/MulaMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/MullBr0.htm' ,
             'http://www.pro-football-reference.com/coaches/MuncMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/MurpJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/NealGr0.htm' ,
             'http://www.pro-football-reference.com/coaches/NessAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/NessTe0.htm' ,
             'http://www.pro-football-reference.com/coaches/NeveEr0.htm' ,
             'http://www.pro-football-reference.com/coaches/NiedFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/NixoMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/NolaDi0.htm' ,
             'http://www.pro-football-reference.com/coaches/NolaMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/NollCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/NortJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/OBriBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/OConFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/OwenSt0.htm' ,
             'http://www.pro-football-reference.com/coaches/PagaCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/PalmMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/PalmCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/ParcBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/PardJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ParkRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/PateJa0.htm' ,
             'http://www.pro-football-reference.com/coaches/PaytSe0.htm' ,
             'http://www.pro-football-reference.com/coaches/PeppPa0.htm' ,
             'http://www.pro-football-reference.com/coaches/PerkRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/PeteBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/PetiRi0.htm' ,
             'http://www.pro-football-reference.com/coaches/PetrBo0.htm' ,
             'http://www.pro-football-reference.com/coaches/PettMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/PhelJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/PhilJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/PhilBu0.htm' ,
             'http://www.pro-football-reference.com/coaches/PhilWa0.htm' ,
             'http://www.pro-football-reference.com/coaches/PierAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/PollFr0.htm' ,
             'http://www.pro-football-reference.com/coaches/PoolHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/PottEa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ProcRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ProtTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/QuinDa0.htm' ,
             'http://www.pro-football-reference.com/coaches/RalsJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/RamsGa0.htm' ,
             'http://www.pro-football-reference.com/coaches/RaucDi0.htm' ,
             'http://www.pro-football-reference.com/coaches/RaucJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/ReevDa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ReidAn0.htm' ,
             'http://www.pro-football-reference.com/coaches/RhodRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/RiceHo0.htm' ,
             'http://www.pro-football-reference.com/coaches/RichRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/RileMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/RingJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/RiveRo0.htm' ,
             'http://www.pro-football-reference.com/coaches/RobbHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/RobeJ.0.htm' ,
             'http://www.pro-football-reference.com/coaches/RobiEd0.htm' ,
             'http://www.pro-football-reference.com/coaches/RobiJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/RobiTe0.htm' ,
             'http://www.pro-football-reference.com/coaches/RogeCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/RogeDa0.htm' ,
             'http://www.pro-football-reference.com/coaches/RonzGe0.htm' ,
             'http://www.pro-football-reference.com/coaches/RoseTa0.htm' ,
             'http://www.pro-football-reference.com/coaches/RossBo0.htm' ,
             'http://www.pro-football-reference.com/coaches/RuetBa0.htm' ,
             'http://www.pro-football-reference.com/coaches/RushCl0.htm' ,
             'http://www.pro-football-reference.com/coaches/RustRo0.htm' ,
             'http://www.pro-football-reference.com/coaches/RutiSa0.htm' ,
             'http://www.pro-football-reference.com/coaches/RyanBu0.htm' ,
             'http://www.pro-football-reference.com/coaches/RyanRe0.htm' ,
             'http://www.pro-football-reference.com/coaches/RymkLo0.htm' ,
             'http://www.pro-football-reference.com/coaches/SabaLo0.htm' ,
             'http://www.pro-football-reference.com/coaches/SabaNi0.htm' ,
             'http://www.pro-football-reference.com/coaches/SachLe0.htm' ,
             'http://www.pro-football-reference.com/coaches/SalaAn0.htm' ,
             'http://www.pro-football-reference.com/coaches/SandJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/SaunAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/ScanDe0.htm' ,
             'http://www.pro-football-reference.com/coaches/SchiGr0.htm' ,
             'http://www.pro-football-reference.com/coaches/SchiPa0.htm' ,
             'http://www.pro-football-reference.com/coaches/SchmJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/SchnHo0.htm' ,
             'http://www.pro-football-reference.com/coaches/SchoMa0.htm' ,
             'http://www.pro-football-reference.com/coaches/SchwJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/ScotRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ScotTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/SeifGe0.htm' ,
             'http://www.pro-football-reference.com/coaches/ShanMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/ShauCl0.htm' ,
             'http://www.pro-football-reference.com/coaches/ShawLa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ShelAr0.htm' ,
             'http://www.pro-football-reference.com/coaches/SherAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/SherMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/ShipTe0.htm' ,
             'http://www.pro-football-reference.com/coaches/ShipKe0.htm' ,
             'http://www.pro-football-reference.com/coaches/ShofJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/ShulDa0.htm' ,
             'http://www.pro-football-reference.com/coaches/ShulDo0.htm' ,
             'http://www.pro-football-reference.com/coaches/ShurPa0.htm' ,
             'http://www.pro-football-reference.com/coaches/SiesHe0.htm' ,
             'http://www.pro-football-reference.com/coaches/SingMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/SkorNi0.htm' ,
             'http://www.pro-football-reference.com/coaches/SmitCl0.htm' ,
             'http://www.pro-football-reference.com/coaches/SmitJe0.htm' ,
             'http://www.pro-football-reference.com/coaches/SmitLo0.htm' ,
             'http://www.pro-football-reference.com/coaches/SmitMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/SnydBo0.htm' ,
             'http://www.pro-football-reference.com/coaches/SpagSt0.htm' ,
             'http://www.pro-football-reference.com/coaches/SparTo0.htm' ,
             'http://www.pro-football-reference.com/coaches/SpeeMa0.htm' ,
             'http://www.pro-football-reference.com/coaches/SpurSt0.htm' ,
             'http://www.pro-football-reference.com/coaches/StalGe0.htm' ,
             'http://www.pro-football-reference.com/coaches/StanDi0.htm' ,
             'http://www.pro-football-reference.com/coaches/StarBa0.htm' ,
             'http://www.pro-football-reference.com/coaches/StecLe0.htm' ,
             'http://www.pro-football-reference.com/coaches/StepKa0.htm' ,
             'http://www.pro-football-reference.com/coaches/SterJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/StevMa0.htm' ,
             'http://www.pro-football-reference.com/coaches/StinPe0.htm' ,
             'http://www.pro-football-reference.com/coaches/StorCa0.htm' ,
             'http://www.pro-football-reference.com/coaches/StraNo0.htm' ,
             'http://www.pro-football-reference.com/coaches/StraHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/StudEr0.htm' ,
             'http://www.pro-football-reference.com/coaches/StudCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/StydJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/SuthJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/SvarHa0.htm' ,
             'http://www.pro-football-reference.com/coaches/SwitBa0.htm' ,
             'http://www.pro-football-reference.com/coaches/TalbNe0.htm' ,
             'http://www.pro-football-reference.com/coaches/TaylHu0.htm' ,
             'http://www.pro-football-reference.com/coaches/TebeGu0.htm' ,
             'http://www.pro-football-reference.com/coaches/ThomEm0.htm' ,
             'http://www.pro-football-reference.com/coaches/ThomJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/ThorJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/TiceMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/TobiEl0.htm' ,
             'http://www.pro-football-reference.com/coaches/TobiVi0.htm' ,
             'http://www.pro-football-reference.com/coaches/ToddDi0.htm' ,
             'http://www.pro-football-reference.com/coaches/TollRu0.htm' ,
             'http://www.pro-football-reference.com/coaches/TomlMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/TomsJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/TresMa0.htm' ,
             'http://www.pro-football-reference.com/coaches/TrimJi0.htm' ,
             'http://www.pro-football-reference.com/coaches/TuckMe0.htm' ,
             'http://www.pro-football-reference.com/coaches/TurnCl0.htm' ,
             'http://www.pro-football-reference.com/coaches/TurnNo0.htm' ,
             'http://www.pro-football-reference.com/coaches/UrseRu0.htm' ,
             'http://www.pro-football-reference.com/coaches/VanBNo0.htm' ,
             'http://www.pro-football-reference.com/coaches/VentRi0.htm' ,
             'http://www.pro-football-reference.com/coaches/VermDi0.htm' ,
             'http://www.pro-football-reference.com/coaches/VittJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/VoylCa0.htm' ,
             'http://www.pro-football-reference.com/coaches/WallCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/WallRo0.htm' ,
             'http://www.pro-football-reference.com/coaches/WalsAd0.htm' ,
             'http://www.pro-football-reference.com/coaches/WalsBi0.htm' ,
             'http://www.pro-football-reference.com/coaches/WalsCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/WaltJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/WannDa0.htm' ,
             'http://www.pro-football-reference.com/coaches/WateBo0.htm' ,
             'http://www.pro-football-reference.com/coaches/WeavRe0.htm' ,
             'http://www.pro-football-reference.com/coaches/WebsAl0.htm' ,
             'http://www.pro-football-reference.com/coaches/WeirEd0.htm' ,
             'http://www.pro-football-reference.com/coaches/WhelJo0.htm' ,
             'http://www.pro-football-reference.com/coaches/WhisKe0.htm' ,
             'http://www.pro-football-reference.com/coaches/WhitMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/WiggPa0.htm' ,
             'http://www.pro-football-reference.com/coaches/WiggHu0.htm' ,
             'http://www.pro-football-reference.com/coaches/WilkWi0.htm' ,
             'http://www.pro-football-reference.com/coaches/WilkBu0.htm' ,
             'http://www.pro-football-reference.com/coaches/WillGr0.htm' ,
             'http://www.pro-football-reference.com/coaches/WillJe0.htm' ,
             'http://www.pro-football-reference.com/coaches/WillRi0.htm' ,
             'http://www.pro-football-reference.com/coaches/WilsRa0.htm' ,
             'http://www.pro-football-reference.com/coaches/WilsGe0.htm' ,
             'http://www.pro-football-reference.com/coaches/WilsLa0.htm' ,
             'http://www.pro-football-reference.com/coaches/WinnCh0.htm' ,
             'http://www.pro-football-reference.com/coaches/WorkHo0.htm' ,
             'http://www.pro-football-reference.com/coaches/WrayLu0.htm' ,
             'http://www.pro-football-reference.com/coaches/WychSa0.htm' ,
             'http://www.pro-football-reference.com/coaches/WycoDo0.htm' ,
             'http://www.pro-football-reference.com/coaches/YounDo0.htm' ,
             'http://www.pro-football-reference.com/coaches/YounSw0.htm' ,
             'http://www.pro-football-reference.com/coaches/ZimmMi0.htm' ,
             'http://www.pro-football-reference.com/coaches/ZornJi0.htm' 
)

# make list of lists of tables from the sites
coaches.tables.lists <- list()
for (i in 1:length(urlList$V1)) {
  # get all tables from page
  Sys.sleep(1)
  coaches.tables.lists[[i]] <- readHTMLTable(urlList$V1[i])
  # parse URL for scraping
  testURL <- getURL(urlList$V1[i], followlocation = TRUE)
  
  # get basic info on coaches, add to list of data frames
  end <- nchar(urlList$V1[i])-4
  coachLabel <- substr(urlList$V1[i], 47, end)
  coachName <- rm_between(testURL, '<p><strong>', '<', extract = TRUE)[[1]][[1]]
  coachBirth <- rm_between(testURL, '" data-birth="', '">', extract = TRUE)[[1]]
  coachLastLiving <- 
    rm_between(testURL, '" data-death="', '">', extract = TRUE)[[1]]
  coaches.tables.lists[[i]]$coaching_basic <- data.frame(
    Label = coachLabel,
    Name = coachName,
    Birth = coachBirth,
    lastLiving = coachLastLiving)
  
  # get list of players who played for coaches, add to list of data frames
  extendedURL <- paste0(substr(urlList$V1[i], 1, 53),"_register.htm")
  coaches.tables.lists[[i]]$coaching_playerRegister <- 
    readHTMLTable(extendedURL)
  
  # print progress
  print(paste("Added coach: ", coachName))
}

# Create data.frame of coaching results tables, along with matching info
tempList <- list()
for (i in 1:length(coaches.tables.lists)) {
  tempList[[i]] <- data.frame(
    coaches.tables.lists[[i]]$coaching_basic,
    coaches.tables.lists[[i]]$coaching_results)
  }
tempDF <- tempList[[1]]
for (i in 1:(length(tempList)-1)) {
  tempDF <- merge(x = tempDF, y = tempList[[(i+1)]],
                  all.x = TRUE, all.y = TRUE,
                  sort = FALSE)
}
head(tempDF)

# Fix column classes  
tempDF$Birth          <- as.Date(as.character(tempDF$Birth))
tempDF$lastLiving     <- as.Date(as.character(tempDF$lastLiving))
tempDF$Year           <- as.numeric(as.character(tempDF$Year))
tempDF$Age            <- as.numeric(as.character(tempDF$Age))
tempDF$Games          <- as.numeric(as.character(tempDF$G))
tempDF$Wins           <- as.numeric(as.character(tempDF$W))
tempDF$Losses         <- as.numeric(as.character(tempDF$L))
tempDF$Ties           <- as.numeric(as.character(tempDF$T))
tempDF$winPerc        <- as.numeric(as.character(tempDF$W.L.))
tempDF$Games.plyf     <- as.numeric(as.character(tempDF$G.plyf))
tempDF$Wins.plyf      <- as.numeric(as.character(tempDF$W.plyf))
tempDF$Losses.plyf    <- as.numeric(as.character(tempDF$L.plyf))
tempDF$winPerc.plyf   <- as.numeric(as.character(tempDF$W.L..1))
tempDF$Rank           <- as.numeric(as.character(tempDF$Rank))
tempDF$Challenges     <- as.numeric(as.character(tempDF$Num))
tempDF$ChallengesWon  <- as.numeric(as.character(tempDF$Won))
tempDF$lastLiving[is.na(tempDF$lastLiving)] <- Sys.Date()
tempDF$G <- NULL
tempDF$W <- NULL
tempDF$L <- NULL
tempDF$T <- NULL
tempDF$W.L. <- NULL
tempDF$G.plyf <- NULL
tempDF$W.plyf <- NULL
tempDF$L.plyf <- NULL
tempDF$W.L..1 <- NULL
tempDF$Num <- NULL
tempDF$Won <- NULL

# Order by labels alphabetically and year, generate UID primary key
coachingResults <- tempDF[order(tempDF$Label, tempDF$Year), ]
coachingResults$UID <- seq(1, nrow(coachingResults), 1)
rm(tempList, tempDF)

# Create data.frame of coaches registries, along with basic info for matching
tempList <- list()
for (i in 1:length(coaches.tables.lists)) {
  tempList[[i]] <- data.frame(
    coaches.tables.lists[[i]]$coaching_basic,
    coaches.tables.lists[[i]]$coaching_playerRegister)
}
tempDF <- tempList[[1]]
for (i in 1:(length(tempList)-1)) {
  tempDF <- merge(x = tempDF, y = tempList[[(i+1)]],
                  all.x = TRUE, all.y = TRUE,
                  sort = FALSE)
}
head(tempDF)

# Fix column classes  
tempDF[, c(5, 8:27)]    <- apply(tempDF[, c(5, 8:27)], 2, 
                                 function(x) as.numeric(as.character(x)))

tempDF$Birth            <- as.Date(as.character(tempDF$Birth))
tempDF$Player           <- tempDF$player_register.
names(tempDF[, c(5, 7:27)]) <- c("playerRank", 
                                 "playerPosition",
                                 "playerFirstYear",
                                 "playerLastYear",
                                 "playerCarAV",
                                 "playerGames",
                                 "playerPassCompletions",
                                 "playerPassAttempts",
                                 "playerPassYards",
                                 "playerPassTD",
                                 "playerPassLng",
                                 "playerPassInt",
                                 "playerPassSk",
                                 "playerPassSkYds",
                                 "playerRushAttempts",
                                 "playerRushYards",
                                 "playerRushTD",
                                 "playerRushLng",
                                 "playerRecs",
                                 "playerRecYards",
                                 "playerRecTD",
                                 "playerRecLng")
tempDF$lastLiving       <- NULL
tempDF$player_register. <- NULL

coachingPlayers <- tempDF[order(tempDF$Label, tempDF$Player), ]
coachingPlayers$UID <- seq(1, nrow(coachingPlayers), 1)

rm(tempList, tempDF)

# TODO: think of questions for the coaching results table
#   figure out a way to match this info to armchair info - probably team/year
#   CLEAN, CLEAN, CLEAN (as of 1-9-2016 haven't really done much)
